### ISSUE TITLE
specify minimum versions of dependencies

### ISSUE THREAD

**Issue by anilbey** [LMBooth/pybci#1]
Hello,

Could you specify the minimum required versions of these dependencies?

https://github.com/LMBooth/pybci/blob/118ecbd2227ef056f46351912ec716e6cba2482b/setup.py#L102C1-L108C16

This issue is part of [#5706](https://github.com/openjournals/joss-reviews/issues/5706).

**Comment by LMBooth** [comment]
Hi @anilbey,
I've added minimum required version in [setup.py](https://github.com/LMBooth/pybci/blob/main/setup.py).

I've also added some[ text to the main page ](https://github.com/LMBooth/pybci#prerequisite-for-non-windows-users) of the git explaining which versions are supported and warning previous versions have not been tested.

**Comment by anilbey** [comment]
Looks great, thanks @LMBooth
