### ISSUE TITLE
DOC: statement of need

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#11]
According to the JOSS requirements, the documentation should contain the following:

> Do the authors clearly state what problems the software is designed to solve and who the target audience is?

Please make sure this goes into the overview / "What is PyBCI" section.

Ping https://github.com/openjournals/joss-reviews/issues/5706

**Comment by LMBooth** [comment]
added a dedicated statement of need in the[ "What is PyBCI" page](https://pybci.readthedocs.io/en/latest/BackgroundInformation/What_is_PyBCI.html#statement-of-need)
