### ISSUE TITLE
ENH: consider implementing a command line interface

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#12]
The first thing I tried after installing pybci was running `pybci` via the command line, but this command was not recognized. Perhaps I have a bias towards CLIs, but I think it would be useful to use argparse to implement a simple command or two. At the least, I think it would be useful to be able to type `pybci --help` in order to get a description of what the tool is and what it can do.

In addition, this is up to your discretion, but I think it would be useful to have some sort of toy example that can be run via the command line. E.g. `pybci hello-world`, which then starts the pseudo-device and runs pybci with some sort of minimal visualization.

If something like this is implemented, a relevant description could also form part of the "Getting started" section in the docs.

Ping https://github.com/openjournals/joss-reviews/issues/5706

**Comment by LMBooth** [comment]
Excellent recommendation @jsheunis , i've now implemented 4 simple tests that can be run right from the command line. The pseudodevice can be initiated as a command too. I'll close this issue for now and keep #14 open until i finish the complementary documentation.
