### ISSUE TITLE
DOC: inconsistent syntax highlighting

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#13]
I've noticed on several pages of the docs that class names or python expressions or similar are not always rendered in the expected syntax highlighting. E.g. className vs ``className`` or X = 1 vs ``X = 1``. Please run through all the docs again to make sure you use this consistently.

Ping https://github.com/openjournals/joss-reviews/issues/5706

**Comment by LMBooth** [comment]
Hi @jsheunis, i've had a comb over and standardised so all py attributes, methods and classes are highlighted appropriately and all variables/equations are now in plain text too. Thanks for spotting this.
