### ISSUE TITLE
TEST: there are no tests or CI implementation

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#15]
There aren't any unit or integration tests, e.g. with [pytest](https://docs.pytest.org/en/7.4.x/) and no continuous integration implementation, e.g. with [appveyor](https://www.appveyor.com/). Adding these components are essential to ensure that the package runs successfully on multiple platforms and that new code contributions don't cause unintended breakage. It is also useful and encouraged for developers to run tests on their own systems before creating a PR with their contributions to your code base.

Ping https://github.com/openjournals/joss-reviews/issues/5706

**Comment by LMBooth** [comment]
We now have appveyor tests, i would like to extend the appveyor tests to two or three more use cases before closing this issue.

Thankyou for recommending these tests and enhancements @jsheunis. I have to admit it was a learning curve as i haven't developed used an automated testing service before like appveyor which is awesome an addition and  I'm glad you recommended it.

**Comment by LMBooth** [comment]
I've extended to 5tests to cover: simple implementation, the pseudo device creation, sklearn, tensorflow and pytorch.
