### ISSUE TITLE
LSL installation instructions are missing

### ISSUE THREAD

**Issue by anilbey** [LMBooth/pybci#2]
Hi,

I followed the instructions on the README and got this error.

```python

>>> import pybci

RuntimeError: LSL binary library file was not found. Please make sure that the binary file can be found in the package lib folder
 (/my-env-path/pybci/lib/python3.10/site-packages/pylsl/lib)
 or the system search path. Alternatively, specify the PYLSL_LIB environment variable.
 You can install the LSL library with conda: `conda install -c conda-forge liblsl`
or otherwise download it from the liblsl releases page assets: https://github.com/sccn/liblsl/releases
```

* Could you mention in the installation section that LSL is a dependency and needs to be installed explicitly?
* If there are any recommended installation instructions, could you provide those for the supported operating systems?
* Could you also outline the supported operating systems e.g. linux windows mac?

This issue is part of https://github.com/openjournals/joss-reviews/issues/5706.

**Comment by LMBooth** [comment]
Hi @anilbey!

Thankyou for pointing this out.
The liblsl dependency is wrapped up with pylsl and should have been installed when downloading pybci by being defined in the 'install_requires'  list provided in setup.py, i'm at work right now but i'll have a go on a clean install of python when i get home to investigate further.

Thankyou again and i'll get in touch when i've had chance to have a play.

**Comment by LMBooth** [comment]
Do you have a Mac @anilbey? I've just got my friend to check on his Mac and he had a similar error,  if so does `brew install labstreaminglayer/tap/lsl` fix for you?  

I'll add some additional instructions to the git and read the docs specifically for Mac in this case, I'll see him tomorrow and have check the process for myself. I'll also double check on an ubuntu machine tomorrow too.

**Comment by anilbey** [comment]
I am on an Ubuntu 22.04.

> I'll add some additional instructions to the git and read the docs specifically for Mac in this case

That's great.

**Comment by LMBooth** [comment]
Ahh, i've just seen pylsl does specify in the [prerequisites](https://github.com/labstreaminglayer/pylsl#prerequisites) section that non windows users need to source liblsl, i'll update my installation instructions to notify people accordingly and direct them to the [liblsl repo](https://github.com/sccn/liblsl) for specific instructions.

Thank you again for bringing this up @anilbey.

**Comment by LMBooth** [comment]
Hi again @anilbey ,

I've made some changes to the installation instructions on the[ main github page](https://github.com/LMBooth/pybci#prerequisite-for-non-windows-users) and [read the docs](https://github.com/LMBooth/pybci#prerequisite-for-non-windows-users), if you find they are insufficient please do say and i can expand where needed. If they are sufficient we can close the issue.

**Comment by anilbey** [comment]
Hi @LMBooth , the "[pylsl repository](https://github.com/LMBooth/pybci/blob/main/home/liam/.local/lib/python3.10/site-packages/pylsl/lib)" link on the readme seems to be broken. It forwards here: https://github.com/LMBooth/pybci/blob/main/home/liam/.local/lib/python3.10/site-packages/pylsl/lib

**Comment by anilbey** [comment]
The 2nd link was sufficient for me, I can install it now.

**Comment by LMBooth** [comment]
Silly me! I'll fix that now.

**Comment by anilbey** [comment]
Thanks, looks good.
