### ISSUE TITLE
Out of place TensorFlow message on command line help call

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#20]
I get the following when I run `pybci --help` from the command line:

```
> pybci --help

2023-10-27 09:53:10.009809: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
usage: pybci [-h] {testSimple,testSklearn,testTensorflow,testPyTorch,createPseudoStreams} ...
```

It seems a bit out of context, perhaps it's useful to handle this programmatically and either catch+ignore it or add more context for the user?

Additionally, it takes several seconds after executing the call and before this message appears. I suspect some calls to tensorflow or some imports are being made (I haven't looked at the code). But it seems like these calls might be unnecessary if the only goal is to show a help docstring with this specific command line call.

**Comment by LMBooth** [comment]
Great catch @jsheunis, I've overlooked my importing of pytorch and tensorflow to bring the whole libraries in when checking which type of model has been passed to pybci, which is called from my root __init__.py. I've now specified which imports are needed instead of bringing in the whole package which has sped up the loading time of the cli as well as tests. I'll upload and let the CI tests run (thanks again for recommending that too!).

I'm a little unsure how to speed it up so --help would be more instantaneous beyond my current change.

**Comment by LMBooth** [comment]
> I get the following when I run `pybci --help` from the command line:
> 
> ```
> > pybci --help
> 
> 2023-10-27 09:53:10.009809: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> usage: pybci [-h] {testSimple,testSklearn,testTensorflow,testPyTorch,createPseudoStreams} ...
> ```
> 
> It seems a bit out of context, perhaps it's useful to handle this programmatically and either catch+ignore it or add more context for the user?

Hopefully now i've changed the cli to only import depending on the scripts used this warning will should only be given when using `pybci testTensorflow`, ~~please let me know if this is not the case.~~ Update, i've added macOS and ubuntu in to the appveyor process so *hopefully* i'll be able to see if these warnings persist.

**Comment by LMBooth** [comment]
I'm having issue getting python 3.9 to install on ubuntu in the appveyor process, as a lot of the pybci dependencies requires python 3.9+, once i've got appveyor working for mac and linux i'll close the issue.

**Comment by jsheunis** [comment]
I updated to version 1.3.4 and I still have the same issue:

```
> time (pybci --help)

2023-10-28 15:07:33.733474: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
usage: pybci [-h] {testSimple,testSklearn,testTensorflow,testPyTorch,createPseudoStreams} ...

PyBCI: A Brain-Computer Interface package. Visit https://pybci.readthedocs.io/en/latest/ for more information!

options:
  -h, --help            show this help message and exit

Commands:
  Available example commands

  {testSimple,testSklearn,testTensorflow,testPyTorch,createPseudoStreams}
    testSimple          Runs simple setup where sklearn support-vector-machine is used for model and pseudodevice generates 8
                        channels of 3 marker types and baseline. Similar to the testSimple.py in the examples folder.
    testSklearn         Sklearn multi-layer perceptron is used for model and pseudodevice generates 8 channels of 3 marker types
                        and baseline. Similar to the testSklearn.py in the examples folder.
    testTensorflow      Tensorflow GRU is used for model and pseudodevice generates 8 channels of 3 marker types and baseline.
                        Similar to the testTensorflow.py in the examples folder.
    testPyTorch         PyTorch neural network is used for model. Similar to the testPytorch.py in the examples folder.
    createPseudoStreams
                        Creates basic Pseudo Device data and marker Lab Streaming Layer (LSL) streams.
( pybci --help; )  7.18s user 2.08s system 80% cpu 11.513 total
```

**Comment by LMBooth** [comment]
Sorry for the delay @jsheunis , i've spent the last day (and 200 commits) battling the appveyor ubuntu2204 build, for some reason my marker stream can't be found in my [LSLScanner script](https://github.com/LMBooth/pybci/blob/main/pybci/Utils/LSLScanner.py) even though it prints that the marker is sent in the [PseudoDevice script](https://github.com/LMBooth/pybci/blob/main/pybci/Utils/PseudoDevice.py) and the LSL data stream is found fine. 

I've finally taken a break from ubuntu (for my sanity) and swapped to the mac build process to see if i can at least iron out that process until i have my hands on an ubuntu machine later in the week.

**Comment by jsheunis** [comment]
No worries, I assumed it was fixed without checking. All in good time :)

**Comment by jsheunis** [comment]
Ping: https://github.com/openjournals/joss-reviews/issues/5706

**Comment by LMBooth** [comment]
Hi @jsheunis , 

When i tested on Mac the CLI doesn't produce this warning now.

The only time i do see it is in the Appveyor output for pytest.ini, but any general calls should be suppressed. Please do re-open if you can still find this issue.
