### ISSUE TITLE
Enable RTD pull request builds

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#23]
This will allow a test on PR to see if the docs will build correctly on rtd.

https://docs.readthedocs.io/en/stable/guides/pull-requests.html

**Comment by jsheunis** [comment]
Ping: https://github.com/openjournals/joss-reviews/issues/5706

**Comment by LMBooth** [comment]
@jsheunis thankyou for the recommendation! Saved the new configuration to test the docs on PR.
