### ISSUE TITLE
Constant warning messages while running the exercises

### ISSUE THREAD

**Issue by anilbey** [LMBooth/pybci#25]
Hi, I am having difficulty running the exercises.

I installed `pybci` and tried the following tests under the Examples directory

- testSimple.py
- testSklearn.py

Both of them keep giving the following warnings in a loop.

```
PyBCI: [WARNING] - No Marker streams available, make sure your accepted marker data Type have been set in bci.lslScanner.markerTypes correctly.
PyBCI: [WARNING] - No data streams available, make sure your streamTypes have been set in bci.lslScanner.dataStream correctly.

```

In `testSimple.py` only the first 2 print messages below are displayed. The rest of them do not get displayed.

> Starting bci
> attemting connect to bci

Am I missing some dependency/configuration? Are the examples running fine on the CI? 

The full log is below. The system I am testing is an Ubuntu 22.04 LTS

```
❯ python testSimple.py
Starting bci
2023-10-29 20:13:50.492 (   1.384s) [python          ]      netinterfaces.cpp:89    INFO| netif 'lo' (status: 1, multicast: 0, broadcast: 0)
2023-10-29 20:13:50.492 (   1.384s) [python          ]      netinterfaces.cpp:89    INFO| netif 'enp0s31f6' (status: 1, multicast: 4096, broadcast: 2)
2023-10-29 20:13:50.492 (   1.384s) [python          ]      netinterfaces.cpp:89    INFO| netif 'lo' (status: 1, multicast: 0, broadcast: 0)
2023-10-29 20:13:50.492 (   1.384s) [python          ]      netinterfaces.cpp:89    INFO| netif 'enp0s31f6' (status: 1, multicast: 4096, broadcast: 2)
2023-10-29 20:13:50.492 (   1.384s) [python          ]      netinterfaces.cpp:102   INFO|       IPv4 addr: c0a80108
2023-10-29 20:13:50.492 (   1.384s) [python          ]      netinterfaces.cpp:89    INFO| netif 'lo' (status: 1, multicast: 0, broadcast: 0)
2023-10-29 20:13:50.492 (   1.384s) [python          ]      netinterfaces.cpp:89    INFO| netif 'enp0s31f6' (status: 1, multicast: 4096, broadcast: 2)
2023-10-29 20:13:50.492 (   1.384s) [python          ]      netinterfaces.cpp:105   INFO|       IPv6 addr: 2a04:ee41:82:7519:76d7:8d91:667c:f269
2023-10-29 20:13:50.492 (   1.384s) [python          ]      netinterfaces.cpp:89    INFO| netif 'enp0s31f6' (status: 1, multicast: 4096, broadcast: 2)
2023-10-29 20:13:50.492 (   1.384s) [python          ]      netinterfaces.cpp:105   INFO|       IPv6 addr: 2a04:ee41:82:7519:55b3:6db:9a75:4d6b
2023-10-29 20:13:50.492 (   1.384s) [python          ]      netinterfaces.cpp:89    INFO| netif 'enp0s31f6' (status: 1, multicast: 4096, broadcast: 2)
2023-10-29 20:13:50.492 (   1.384s) [python          ]      netinterfaces.cpp:105   INFO|       IPv6 addr: fe80::f07c:2a0a:1f5d:1f06%enp0s31f6
2023-10-29 20:13:50.492 (   1.384s) [python          ]         api_config.cpp:270   INFO| Loaded default config
PyBCI: [INFO] - Invalid or no sklearn classifier passed to clf. Checking tensorflow model... 
2023-10-29 20:13:52.689121: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-29 20:13:52.689167: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-29 20:13:52.689206: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-29 20:13:52.695314: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-29 20:13:53.352814: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
PyBCI: [INFO] - Invalid or no tensorflow model passed to model.  Checking pytorch torchModel...
PyBCI: [INFO] - Invalid or no PyTorch model passed to model. Defaulting to SVM by SkLearn
attemting connect to bci
PyBCI: [WARNING] - No Marker streams available, make sure your accepted marker data Type have been set in bci.lslScanner.markerTypes correctly.
PyBCI: [WARNING] - No data streams available, make sure your streamTypes have been set in bci.lslScanner.dataStream correctly.
PyBCI: [WARNING] - No Marker streams available, make sure your accepted marker data Type have been set in bci.lslScanner.markerTypes correctly.
PyBCI: [WARNING] - No data streams available, make sure your streamTypes have been set in bci.lslScanner.dataStream correctly.
PyBCI: [WARNING] - No Marker streams available, make sure your accepted marker data Type have been set in bci.lslScanner.markerTypes correctly.
...
```

This is part of the https://github.com/openjournals/joss-reviews/issues/5706 review.

**Comment by LMBooth** [comment]
Hi @anilbey thank you for trying, this also relates to issue #24. For unix based operating systems there is an issue with starting lsl threads outside of the main thread, I'd only tested the pseudo device on my windows machine but since integrating in to appveyor I've been attempting a fix and plan to update the documentation accordingly where the user will be required to initialise the pseudo device and pass as an argument to the pybci class.

I'll be home later in the week and will hopefully have a fix when appveyor returns that all the tests complete successfully.

**Comment by LMBooth** [comment]
Hi again @anilbey, for an update of where i've progressed to - i have the mac distribution working with the pytests on appveyor, however Linux is proving far more problematic. When creating two lsl outlets the second creation seems to overwrite the first meaning  only one stream (either data or marker depending on order of creation) will be seen on the network. I've opened an [issue on the pylsl git here](https://github.com/labstreaminglayer/pylsl/issues/74) to see if they have any suggestions of how to overcome this issue. 

If it's not possible then i may have to omit the PseudoDevice class from Linux meaning no automated tests can be run and only streaming hardware would be compatible. I'm curious to know your thoughts on this (should i omit the PseudoDevice or just say pybci does not support Linux) and if you have a windows/mac OS available to verify functionality on?

**Comment by anilbey** [comment]
Hello @LMBooth thanks for the information.

Given that the underlying technologies (Python, LSL and pylsl) support cross-platform use, it would be unusual for software built upon them to not offer the same level of compatibility.

The bcipy package, which was mentioned in the 'state of the field' section of your paper,  operates on the three major operating systems as well: [bcipy GitHub Actions](https://github.com/CAMBI-tech/BciPy/actions/runs/6724778648).

I can run the tests on Mac and Windows, but is the package not going to work on Linux? 

Also I'm curious, does the PseudoDevice (used in tests and examples) have to depend on the pylsl implementation? Can it not generate and stream mock data without having a dependency on pylsl?

**Comment by LMBooth** [comment]
Hi @anilbey, thankyou for the quick response. 

It is an odd error and i'm wondering if it may be due to recent updates in the LSL packages since my previous example worked a few months ago which upon review follows the same methodology of lsl creation. I'm going to set the download for lsl to be an earlier version on linux to see if the tests run successfully, if so i can notify the maintainers of pyLSL that there is an issue.

PyLSL would ideally be the way to create pseudo streams for data and markers since this is the method data would be input from [many off the shelf devices ](https://labstreaminglayer.readthedocs.io/info/supported_devices.html)  or markers from software like Unity,  PsychoPy, or custom languages interfaces be it C, C++, python, Java, MATLAB. 

I'll post an update if any previous versions of the liblsl.so has any luck or not.

**Comment by LMBooth** [comment]
Okayyyy, reverting to earlier liblsl.so versions or pylsl versions didn't help, though if i run my old separate script in one terminal and set pseudodevice to false in another the tests work on ubuntu. 

To speed things up I've partitioned my home machine and installed Ubuntu on it too so i don't need to go in the office to check or do it via appveyor anymore so that will hopefully speed up finding a fix, i'm thinking if i can make the original pseudodevice script run fine then i could take a part of that and subprocess to it so i create another instance of python, *fingers crossed* that'll do it?

I'm out tomorrow day and evening with friends but will hopefully be able to get something working come Sunday night. So sorry about this @anilbey

**Comment by LMBooth** [comment]
Hi @anilbey , so i have changed the pseudo device class to separate out the threaded and multi-processed functions as i had the multi-processed functions called in the same class inheriting self. Multiprocessing in Windows and Mac is spawned where in Linux it's forked, i believe this is why there was an issue. Now i have the program working correctly on my own Linux build (22.04) and Python version (3.10.12) however it still can only find one stream in the appveyor process. 

Do you have any success if you try to install and run an example of pybci 1.4.3?

**Comment by emdupre** [comment]
Thank you for identifying and working on this, @anilbey and @LMBooth ! @anilbey, please let us know when you've had an opportunity to assess the proposed fix in v1.4.3.

**Comment by anilbey** [comment]
So on v1.4.3
```
❯ pip list | grep pybci
pybci-package                1.4.3
```

Errors occur while running the tests.
```
2023-11-14 17:11:52.914 ( 111.886s) [R_PyBCIPseudoM  ]      data_receiver.cpp:344    ERR| Stream transmission broke off (Input stream error.); re-connecting...
2023-11-14 17:11:52.918 ( 111.889s) [R_PyBCIPseudoD  ]      data_receiver.cpp:344    ERR| Stream transmission broke off (Input stream error.); re-connecting...
PyBCI: [INFO] - Threads stopped.
.
Tests/test_Simple.py PyBCI: [INFO] -Initialised PseudoDevice...
PyBCI: [INFO] - PseudoDevice - Begin streaming.
PyBCI: [INFO] - PseudoDevice - sending marker Marker1
PyBCI: [INFO] - Found stream name: PyBCIPseudoDataStream
PyBCI: [INFO] - Found stream type: EMG
PyBCI: [INFO] - Found stream name: LSL_Tags
PyBCI: [INFO] - Found stream type: Tags
PyBCI: [INFO] - Found stream name: PyBCIPseudoMarkers
PyBCI: [INFO] - Found stream type: Markers
PyBCI: [INFO] - Invalid or no sklearn classifier passed to clf. Checking tensorflow model...
PyBCI: [INFO] - Invalid or no tensorflow model passed to model.  Checking pytorch torchModel...
PyBCI: [INFO] - Invalid or no PyTorch model passed to model. Defaulting to SVM by SkLearn
PyBCI: [INFO] - Found stream name: PyBCIPseudoDataStream
PyBCI: [INFO] - Found stream type: EMG
PyBCI: [INFO] - Found stream name: LSL_Tags
PyBCI: [INFO] - Found stream type: Tags
PyBCI: [INFO] - Found stream name: PyBCIPseudoMarkers
PyBCI: [INFO] - Found stream type: Markers
PyBCI: [INFO] - Success - 1 data stream(s) found, 1 marker stream found
PyBCI: [INFO] - Starting threads initialisation...
PyBCI: [INFO] - Threads initialised.
PyBCI: [INFO] - Started training...
PyBCI: [INFO] - PseudoDevice - sending marker Marker2
PyBCI: [INFO] - PseudoDevice - sending marker Marker3
PyBCI: [INFO] - PseudoDevice - sending baseline
PyBCI: [INFO] - PseudoDevice - sending marker Marker1
PyBCI: [INFO] - PseudoDevice - sending marker Marker2
PyBCI: [INFO] - PseudoDevice - sending marker Marker3
PyBCI: [INFO] - PseudoDevice - sending baseline
PyBCI: [INFO] - PseudoDevice - sending marker Marker1
2023-11-14 17:13:24.117 ( 203.088s) [R_PyBCIPseudoM  ]      data_receiver.cpp:344    ERR| Stream transmission broke off (Input stream error.); re-connecting...
2023-11-14 17:13:24.123 ( 203.094s) [R_PyBCIPseudoD  ]      data_receiver.cpp:344    ERR| Stream transmission broke off (Input stream error.); re-connecting...
PyBCI: [INFO] - Threads stopped.
```

**Comment by LMBooth** [comment]
> 2023-11-14 17:13:24.117 ( 203.088s) [R_PyBCIPseudoM  ]      data_receiver.cpp:344    ERR| Stream transmission broke off (Input stream error.); re-connecting...
> 2023-11-14 17:13:24.123 ( 203.094s) [R_PyBCIPseudoD  ]      data_receiver.cpp:344    ERR| Stream transmission broke off (Input stream error.); re-connecting...


Hi  @anilbey, these are generated in the LSL libraries instead of pybci when the receiver inlets are disconnected, which occurs when the Pseudo Device outlets are closed at the end of the test, it looks like the test was successful.

**Comment by anilbey** [comment]
But it is later followed by a segmentation fault.


```
PyBCI: [INFO] - Starting threads initialisation...
PyBCI: [INFO] - Threads initialised.
PyBCI: [INFO] - Started training...
2023-11-14 17:18:40.831 ( 519.803s) [R_PyBCIPseudoM  ]      data_receiver.cpp:344    ERR| Stream transmission broke off (Input stream error.); re-connecting...
2023-11-14 17:18:40.833 ( 519.804s) [R_PyBCIPseudoD  ]      data_receiver.cpp:344    ERR| Stream transmission broke off (Input stream error.); re-connecting...
PyBCI: [INFO] - Threads stopped.

Timeout reached. Stopping threads.
.
Tests/test_zDualStream.py Fatal Python error: Segmentation fault

```

**Comment by anilbey** [comment]
Here also, another one


```PyBCI: [INFO] - Invalid or no sklearn classifier passed to clf. Checking tensorflow model...
PyBCI: [INFO] - Invalid or no tensorflow model passed to model.  Checking pytorch torchModel...
PyBCI: [INFO] - Invalid or no PyTorch model passed to model. Defaulting to SVM by SkLearn
PyBCI: [INFO] - Found stream name: dev2
PyBCI: [INFO] - Found stream type: EMG
PyBCI: [INFO] - Found stream name: LSL_Tags
PyBCI: [INFO] - Found stream type: Tags
PyBCI: [INFO] - Found stream name: dev1
PyBCI: [INFO] - Found stream type: EMG
PyBCI: [WARNING] - No Marker streams available, make sure your accepted marker data Type have been set in bci.lslScanner.markerTypes correctly.
Fatal Python error: Segmentation fault

Current thread 0x00007fd084aa5000 (most recent call first):
  Garbage-collecting


```

**Comment by LMBooth** [comment]
This is odd, when i call `pytest Tests/test_zDualStream.py` and `pytest Tests/test_zSimpleOtherFeatures.py` they both pass fine on Ubuntu 22.04 and Python 3.10.12. Just ran the pytest for all 11 items  to see if it's an ordered effect, but passed with the following output:
```
/Documents/GitHub/pybci$ pytest Tests
================================================================================= test session starts =================================================================================
platform linux -- Python 3.10.12, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/liam/Documents/GitHub/pybci/Tests
configfile: pytest.ini
collected 11 items                                                                                                                                                                    

Tests/test_PseudoDevice.py .                                                                                                                                                    [  9%]
Tests/test_Pytorch.py .                                                                                                                                                         [ 18%]
Tests/test_Simple.py .                                                                                                                                                          [ 27%]
Tests/test_Sklearn.py .                                                                                                                                                         [ 36%]
Tests/test_Tensorflow.py .                                                                                                                                                      [ 45%]
Tests/test_cli.py ....                                                                                                                                                          [ 81%]
Tests/test_zDualStream.py .                                                                                                                                                     [ 90%]
Tests/test_zSimpleOtherFeatures.py .                                                                                                                                            [100%]

================================================================================== warnings summary ===================================================================================
../../../.local/lib/python3.10/site-packages/tensorflow/__init__.py:29
  /home/liam/.local/lib/python3.10/site-packages/tensorflow/__init__.py:29: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    import distutils as _distutils

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================== 11 passed, 1 warning in 656.05s (0:10:56) ======================================================================
```

Does turning off the LSL_Tags stream make a difference?

**Comment by LMBooth** [comment]
or printing the  output from `pytest -s Tests/test_zDualStream.py`:

```
PyBCI: [INFO] - Invalid or no tensorflow model passed to model.  Checking pytorch torchModel...
PyBCI: [INFO] - Invalid or no PyTorch model passed to model. Defaulting to SVM by SkLearn
PyBCI: [INFO] - Found stream name: dev2
PyBCI: [INFO] - Found stream type: EMG
PyBCI: [INFO] - Found stream name: dev1
PyBCI: [INFO] - Found stream type: EMG
PyBCI: [INFO] - Found stream name: PyBCIPseudoMarkers
PyBCI: [INFO] - Found stream type: Markers
PyBCI: [INFO] - Success - 2 data stream(s) found, 1 marker stream found
PyBCI: [INFO] - Starting threads initialisation...
PyBCI: [INFO] - PseudoDevice - sending marker Marker2
PyBCI: [INFO] - Threads initialised.
PyBCI: [INFO] - Started training...
PyBCI: [INFO] - PseudoDevice - sending marker Marker3
PyBCI: [INFO] - PseudoDevice - sending baseline
PyBCI: [INFO] - PseudoDevice - sending marker Marker1
PyBCI: [INFO] - PseudoDevice - sending marker Marker2
PyBCI: [INFO] - PseudoDevice - sending marker Marker3
PyBCI: [INFO] - PseudoDevice - sending baseline
PyBCI: [INFO] - PseudoDevice - sending marker Marker1
PyBCI: [INFO] - PseudoDevice - sending marker Marker2
2023-11-14 16:51:37.578 (  92.421s) [R_dev1          ]      data_receiver.cpp:342    ERR| Stream transmission broke off (Input stream error.); re-connecting...
2023-11-14 16:51:37.584 (  92.427s) [R_PyBCIPseudoM  ]      data_receiver.cpp:342    ERR| Stream transmission broke off (Input stream error.); re-connecting...
2023-11-14 16:51:39.580 (  94.422s) [R_dev2          ]      data_receiver.cpp:342    ERR| Stream transmission broke off (Input stream error.); re-connecting...
PyBCI: [INFO] - Threads stopped.
.

================================================================================== warnings summary ===================================================================================
test_zDualStream.py::test_run_dual
  /home/liam/.local/lib/python3.10/site-packages/tensorflow/__init__.py:29: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    import distutils as _distutils

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================== 1 passed, 1 warning in 103.48s (0:01:43) =======================================================================
```

**Comment by anilbey** [comment]
> Does turning off the LSL_Tags stream make a difference?

I don't know.

 A docker image may help in this case with reproducibility and it will also simplify the installation.

**Comment by LMBooth** [comment]
Ahh

**Comment by LMBooth** [comment]
Ahh, i ask about the LSL_Tags stream as that isn't set by pybci so was unsure if you had other LSL streams running from another source.

I've started putting together a dockerfile in the root of the directory, hopefully i'll have time tomorrow evening to verify and that will give a more clear - and fully-functional! - method of installation for Linux.

**Comment by LMBooth** [comment]
Hi @anilbey , can you run with the [Dockerfile](https://github.com/LMBooth/pybci/blob/main/Dockerfile)?

**Comment by anilbey** [comment]
Thanks a lot @LMBooth for the quick implementation. I am on a leave now and don't have access to a linux machine however I will check it in detail after I return (on the 26th).

**Comment by anilbey** [comment]
Brilliant, I can run both the tests and the examples with the docker image and the instructions provided on the README. 
Tests:
```
11 passed, 1 warning in 640.70s (0:10:40) 
```
Examples:
```
PyBCI: [INFO] - PseudoDevice - sending marker Marker36], 'baseline': [2, 6], 'Marker1': [3, 6]} Accuracy: 1.0         
Markers received: {'Marker2': [0, 6], 'Marker3': [1, 9], 'baseline': [2, 6], 'Marker1': [3, 6]} Accuracy: 1.0 
```

Thanks @LMBooth. I think now this issue can be marked as resolved.

**Comment by LMBooth** [comment]
Excellent, thankyou for providing your input to help resolve this @anilbey, a meme comes to mind:
![image](https://github.com/LMBooth/pybci/assets/31129153/089402a9-28fe-42f9-8470-f71be40de11d)

I've just today extended some of the pytest coverage too to help ensure some of the additional functionality functions correctly.

**Comment by anilbey** [comment]
> I've just today extended some of the pytest coverage too to help ensure some of the additional functionality functions correctly.

Great news!
