### ISSUE TITLE
JOSS: paper title seems redundant

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#3]
> PyBCI: A Python Package for Brain-Computer Interface (BCI) Design/An Open Source Brain-Computer Interface Framework in Python

These two titles seem like different phrasing of the same idea/tool. Is there a reason why both are provided in the title field? I would propose using a single title.

Ping https://github.com/openjournals/joss-reviews/issues/5706

**Comment by LMBooth** [comment]
Thanks for catching this @jsheunis , i think they are both titles i was playing with and hadn't got round to deleting one!

I'll amend now and if you agree its acceptable we can close the issue.
