### ISSUE TITLE
JOSS: clarify hardware capabilities

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#4]
Generally, BCI's could work with any number of related acquisition hardware, including MRI, EEG, fNIRS, etc. People who aren't familiar with LSL might not know which hardware is being referred to and thus with which hardware PyBCI can be used. You do mention:

> The software uses the Lab Streaming Layer (LSL) [@lsl] protocol for data acquisition on various LSL enabled data streams...

but I think this is still too generic. I suggest adding some reference to hardware capabilities in the summary already to make it clearer from the start.

Ping https://github.com/openjournals/joss-reviews/issues/5706

**Comment by LMBooth** [comment]
Hi @jsheunis , i've made a slight edit here, so now i specify what the LSL does and provided a link to supported hardware. Do you think this could be more applicable? I'd rather provide a link to available hardware then necessarily supply a list of supported devices as technically any time series device can be used, like xbox controllers, wii remotes, mice and keyboards.

Here's the updated summary section which hopefully is more clear, if you can see any issues or recommendation please do say:
"PyBCI is a comprehensive, open-source Python framework developed to facilitate brain-computer interface (BCI) research. It encompasses data acquisition, data labelling, feature extraction, and machine learning. PyBCI provides a streamlined, user-friendly platform for creating real-time BCI applications. The software uses the Lab Streaming Layer (LSL) [@lsl] protocol for the unified collection of time-series measurement that handles both the networking, time-synchronization and (near-) real-time access (supported LSL devices found here: https://labstreaminglayer.readthedocs.io/info/supported_devices.html). At least one LSL data stream is required and a single marker stream is used for labelling training data."

**Comment by jsheunis** [comment]
I think the added information is useful, but not necessarily in the summary because it adds technical-heavy content that detracts from the purpose of the summary. See my related comment here: https://github.com/LMBooth/pybci/issues/7

I think if you provide a more concise statement in the summary to indicate that it works with time series data from a wide variety of LSL-compatible hardware sources, then the more technical statement can be provided further down in the paper.

**Comment by LMBooth** [comment]
Agreed! I had a re-read of the whole thing and realised this myself, seeing that i provide more description of the LSL later too so it is quite unnecessary in the summary. I should be able to get round to amending this with the other points discussed in #7 over the next couple days. Thankyou for taking the time to review the paper so far!

**Comment by lsl** [comment]
How does something like this sound?

Summary:
> PyBCI is an open-source Python framework designed for brain-computer interface (BCI) research. Compatible with the time series data from a wide array of LSL-compatible hardware sources it provides the tools necessary for real-time BCI application development.

Technical:
> PyBCI makes use of the Lab Streaming Layer (LSL) protocol enabling a unified collection of time-series measurement data. PyBCI handles both the networking, time-synchronization and (near-) real-time access.
>
> For a list of supported LSL devices, please refer to: https://labstreaminglayer.readthedocs.io/info/supported_devices.html. Additionally, PyBCI requires at least one LSL data stream for operation, with a single marker stream used for training data labeling.

**Comment by LMBooth** [comment]
Thanks for adding @lsl , your git hub name (and im assuming initials) is ideal to join in this conversation.
