### ISSUE TITLE
PyPI package name

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#6]
I could only find your package on PyPI: https://pypi.org/search/?q=pybci

Is the conflict with a different package still a problem? If not, I would suggest renaming the package to `pybci`, because the current installation process is slightly confusing with the double "install": https://github.com/LMBooth/pybci/blob/main/docs/BackgroundInformation/Introduction.rst?plain=1#L12-L14

If you can't rename the package, perhaps consider naming it `pybci-installer` instead.

https://github.com/openjournals/joss-reviews/issues/5706

**Comment by LMBooth** [comment]
Hi @jsheunis, thanks for bringing this up, the conflict is still a problem with no response as of yet.

I could rename to pybci-installer if you think this would be preferable and more clear for users, i'll have a look at formalising this tonight when i get home from work.

**Comment by jsheunis** [comment]
actually, on second thought, I don't think my suggestion will be clearer for users. But I also think the current name isn't clear either. The "install" part suggest that you are downloading an installer of some kind, which then needs to be executed in order to install the package. In reality, it is the actual package that's being downloaded and installed. In the end it's your decision, but you could perhaps try a name with some extra characters (perhaps `py-bci` i.e. with a hyphen, or something else that is just not as confusing as `install`).

And then the associated docs would need to be updated.

**Comment by LMBooth** [comment]
`py-bci` , `py.bci` were too similar to another package and i tried `py-bci-`, `-py-bci` which broke pypi naming conventions needing to start and end on a alpha-numeric, so instead i've gone for `pybci-package`, and updated the documentation accordingly, hopefully this is more intuitive.
