### ISSUE TITLE
Installation process suggestions

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#8]
I suggest adding the following to the readme and to the docs:

#### The use of a virtual environment for installing the package, e.g.:

```
python -m venv my_env
source my_env/bin/activate
```
followed by `pip install`

#### Installing from the source on github, for those wanting latest un-released features or for developers:

```
pip install git+https://github.com/LMBooth/pybci.git
```

or

```
git clone https://github.com/LMBooth/pybci.git
cd pybci
pip install -e .
```

Ping https://github.com/openjournals/joss-reviews/issues/5706

**Comment by jsheunis** [comment]
I also think, even though the minimum Python requirement is implicit in the setup.py code, it would be useful to state this explicitly in the docs, ideally in the Installation section.

**Comment by LMBooth** [comment]
Thankyou for these recommendation @jsheunis , i've made them and shall now close this issue. Please drop a comment or re-open if you find any related issues.
