### ISSUE TITLE
DOC: Introduction section seems unintuitive

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#9]
The Introduction section of the docs seems a bit unintuitive. To me, "Introduction" is more about an overview of the tool, and not installation and usage. Currently it contains "Installation", "Simple Implementation", and "What is PyBCI?". I suggest reordering it at the top level to a "Get started" section, which contains all the information a user would need to get started. This would be Installation and Simple Implementation. Then I would move the "What is PyBCI?" into its own section, maybe "Introduction" or "Overview", or even "What is PyBCI"

Ping https://github.com/openjournals/joss-reviews/issues/5706

**Comment by jsheunis** [comment]
I would also add a place for prerequisites before the installation. Then the paragraph about LSL for non-windows systems can move there, and you can also mention the minimum python version.

**Comment by LMBooth** [comment]
Thankyou for these recommendations @jsheunis, i've had a reshuffle and will close the issue for now. Hopefully the information is now presented in a more intuitive manner.
